minor changes

diff --git a/display_rooms b/display_rooms
--- a/display_rooms
+++ b/display_rooms
@@ -21,15 +21,31 @@ echo "9.Neurology"
 echo "10.Nursing"
 read ch1
 
-bid=`nawk -v ch1="$ch1" -F, 'BEGIN{arr[1]="CSCI";arr[2]="Cardiology";arr[3]="ENT";arr[4]="Ortho";arr[5]="Pediatric";arr[6]="Radiology";arr[7]="OPD";arr[8]="Pharmacy";arr[9]="Neurology";arr[10]="Nursing";}{ if ($7 == arr[ch1]){print $1}}' buildings.csv`
+if [[ $ch1 -ge 1 && $ch1 -le 10 ]]
+then
+
+bid=`awk -v ch1="$ch1" -F, 'BEGIN{arr[1]="CSCI";arr[2]="Cardiology";arr[3]="ENT";arr[4]="Ortho";arr[5]="Pediatric";arr[6]="Radiology";arr[7]="OPD";arr[8]="Pharmacy";arr[9]="Neurology";arr[10]="Nursing";}{ if ($7 == arr[ch1]){print $1}}' buildings.csv`
 
 echo "building info"
 echo " "
-nawk -v bid="$bid" -F, '{if (NR == 1){printf "%-15s%-15s%-15s\n",$1,$2,$7}if ($1 == bid) {printf "%-15s%-15s%-15s\n",$1,$2,$7}}' buildings.csv
+awk -v bid="$bid" -F, '{if (NR == 1){printf "%-15s%-15s%-15s\n",$1,$2,$7}if ($1 == bid) {printf "%-15s%-15s%-15s\n",$1,$2,$7}}' buildings.csv
 echo " "
 echo "room info"
 echo " "
-nawk -v bid="$bid" -F, '{if (NR == 1){printf "%-15s%-15s%-15s%-15s%-15s\n",$1,$2,$3,$4,$5}if ($6 == bid) {printf "%-15s%-15s%-15s%-15s%-15s\n",$1,$2,$3,$4,$5}}' rooms.csv
+awk -v bid="$bid" -F, '{if (NR == 1){printf "%-15s%-15s%-15s%-15s%-15s\n",$1,$2,$3,$4,$5}if ($6 == bid) {printf "%-15s%-15s%-15s%-15s%-15s\n",$1,$2,$3,$4,$5}}' rooms.csv
+echo "-------------------------------------------------------------------------------------"
+
+else
+echo "Invalid Input. Try again"
+echo "----------------------------------------------"
+echo "Redirecting to Main Menu"
+echo "----------------------------------------------"
+./menu
+exit 1
+fi
+
+
+
 fi
 
 #-------------DIsplay building details----------------------------------
@@ -51,19 +67,25 @@ read ch1
 if [[ $ch1 -ge 1 && $ch1 -le 10 ]]
 then
 
-bid=`nawk -v ch1="$ch1" -F, 'BEGIN{arr[1]="CSCI";arr[2]="Cardiology";arr[3]="ENT";arr[4]="Ortho";arr[5]="Pediatric";arr[6]="Radiology";arr[7]="OPD";arr[8]="Pharmacy";arr[9]="Neurology";arr[10]="Nursing";}{ if ($7 == arr[ch1]){print $1}}' buildings.csv`
+bid=`awk -v ch1="$ch1" -F, 'BEGIN{arr[1]="CSCI";arr[2]="Cardiology";arr[3]="ENT";arr[4]="Ortho";arr[5]="Pediatric";arr[6]="Radiology";arr[7]="OPD";arr[8]="Pharmacy";arr[9]="Neurology";arr[10]="Nursing";}{ if ($7 == arr[ch1]){print $1}}' buildings.csv`
 
 echo "building info"
 echo " "
-nawk -v bid="$bid" -F, '{if (NR == 1){printf "%-15s%-15s%-15s%-15s%-15s%-15s%-15s\n",$1,$2,$3,$4,$5,$6,$7}if ($1 == bid) {printf "%-15s%-15s%-15s%-15s%-15s%-15s%-15s\n",$1,$2,$3,$4,$5,$6,$7}}' buildings.csv
+awk -v bid="$bid" -F, '{if (NR == 1){printf "%-15s%-15s%-15s%-15s%-15s%-15s%-15s\n",$1,$2,$3,$4,$5,$6,$7}if ($1 == bid) {printf "%-15s%-15s%-15s%-15s%-15s%-15s%-15s\n",$1,$2,$3,$4,$5,$6,$7}}' buildings.csv
 echo " "
 echo "room info"
 echo " "
-nawk -v bid="$bid" -F, '{if (NR == 1){printf "%-15s%-15s%-15s\n",$1,$2,$3}if ($6 == bid) {printf "%-15s%-15s%-15s\n",$1,$2,$3}}' rooms.csv
+awk -v bid="$bid" -F, '{if (NR == 1){printf "%-15s%-15s%-15s\n",$1,$2,$3}if ($6 == bid) {printf "%-15s%-15s%-15s\n",$1,$2,$3}}' rooms.csv
+echo "-------------------------------------------------------------------------------------"
 
 else
 echo "Invalid Input. Try again"
+echo "----------------------------------------------"
+echo "Redirecting to Main Menu"
+echo "----------------------------------------------"
+./menu
 exit 1
+
 fi
 fi
 
@@ -84,11 +106,17 @@ read ch1
 if [[ $ch1 -ge 1 && $ch1 -le 8 ]]
 then
 
-nawk -v ch1="$ch1" -F, 'BEGIN{arr[1]="General";arr[2]="Delivery";arr[3]="Consulting";arr[4]="ICU";arr[5]="Surgery";arr[6]="Day Care";arr[7]="Deluxe";arr[8]="Suite"}
+awk -v ch1="$ch1" -F, 'BEGIN{arr[1]="General";arr[2]="Delivery";arr[3]="Consulting";arr[4]="ICU";arr[5]="Surgery";arr[6]="Day Care";arr[7]="Deluxe";arr[8]="Suite"}
 { if (NR == 1) {printf "%-15s%-15s%-15s%-15s%-15s%-15s\n\n",$1,$2,$3,$4,$5,$6} if ($2 == arr[ch1]) {printf "%-15s%-15s%-15s%-15s%-15s%-15s\n",$1,$2,$3,$4,$5,$6} }' rooms.csv
+echo "-------------------------------------------------------------------------------------"
 
 else
 echo "Invalid Input. Try again"
+echo "----------------------------------------------"
+echo "Redirecting to Main Menu"
+echo "----------------------------------------------"
+./menu
 exit 1
+
 fi
 fi
